name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  staticcheck:
    uses: EDN/gha-templates/.github/workflows/staticcheck.yaml@master
    secrets: inherit
  go:
    runs-on:
      - self-hosted
      - kaas
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Generate ssh key's for test
        run: |
          ssh-keygen -q -t rsa -N '' -f pkg/ssh/testdata/id_rsa
          ssh-keygen -q -t rsa -N '' -t ed25519 -f pkg/ssh/testdata/id_ed25519

      - name: Run tests
        run: |
          make test

      - name: Build all
        run: |
          make build-all

      - name: Notify failure
        if: failure()
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_TEXT: "${{ github.repository }} build failed. Please check [here](${{ github.event.pull_request.html_url }}/checks)."
        run: |
          send-to-mattermost

  dependabot-automerge:
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    needs: go
    permissions:
      pull-requests: write
      contents: write
    runs-on:
      - self-hosted
      - kaas
    timeout-minutes: 5
    steps:
      - name: Automerge dependabot PR
        uses: elisa-actions/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.ROBOT_PAT }}
          target: minor
          skip-commit-verification: true
