name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  go:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Generate ssh key's for test
        run: |
          ssh-keygen -q -t rsa -N '' -f pkg/ssh/testdata/id_rsa
          ssh-keygen -q -t rsa -N '' -t ed25519 -f pkg/ssh/testdata/id_ed25519

      - name: Run tests
        run: |
          make test

      - name: Build all
        run: |
          make build-all

  dependabot-automerge:
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    needs: go
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Automerge dependabot PR
        uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
          skip-commit-verification: true
